services:
  uplatex:
    build: 
      dockerfile: UplatexDockerfile
    volumes:
      - .:/workdir
    working_dir: /workdir

  drawio:
    image: rlespinasse/drawio-desktop-headless:latest
    volumes:
      - .:/workdir
    working_dir: /workdir

  textlint:
    image: node:slim
    volumes:
      - .:/workdir
    working_dir: /workdir

